development:
  adapter: postgresql
  encoding: unicode
  database: cinder_development
  min_messages: warning
  host: localhost
staging:
  adapter: postgresql
  encoding: unicode
  database: cinder_staging
  min_messages: warning
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: cinder_production
  min_messages: warning
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: cinder_test
  min_messages: warning
  host: localhost
